CREATE TABLE CUSTOMER
(
    ID BIGINT PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255)
);

INSERT INTO PUBLIC.CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (1, 'Jack9999', 'Bauer');
INSERT INTO PUBLIC.CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (2, 'ChloeAA', 'O''Brian');
INSERT INTO PUBLIC.CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (3, 'KimAA', 'Bauer');
INSERT INTO PUBLIC.CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (4, 'David', 'Palmer');
INSERT INTO PUBLIC.CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (5, 'Michelle', 'Dessler');
INSERT INTO PUBLIC.CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (6, 'Jack', 'Bauer');
INSERT INTO PUBLIC.CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (7, 'Chloe', 'O''Brian');
INSERT INTO PUBLIC.CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (8, 'Kim', 'Bauer');
INSERT INTO PUBLIC.CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (9, 'David', 'Palmer');
INSERT INTO PUBLIC.CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (10, 'Michelle', 'Dessler');
INSERT INTO PUBLIC.CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (11, 'Jack', 'Bauer');
INSERT INTO PUBLIC.CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (12, 'Chloe', 'O''Brian');
INSERT INTO PUBLIC.CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (13, 'Kim', 'Bauer');
INSERT INTO PUBLIC.CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (14, 'David', 'Palmer');
INSERT INTO PUBLIC.CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (15, 'Michelle', 'Dessler');
